### ISSUE TITLE
Automate the process by cron job implementation through task scheduler (OS - Windows 10)

### ISSUE THREAD

**Issue by Cmastris** [Cmastris/robotstxt-change-monitor#3]
Hi @Cmastris 

I'm trying to automate the process by (**cron job implementation)** through task scheduler (**OS - Windows 10**). 
I created batch file instead of directly adding the python script in scheduler. Batch file contains path to **python.exe** (Application) and path to my "**main.py**" script. 
By manually running the batch file it is working correctly, but when i add that batch file as a program in task scheduler it is not working it is throwing the below error.

C:\windows\system32>C:\Users\suri02\AppData\Local\Programs\Python\Python39\python.exe "D:\Python Tasks\robots txt stuff\main.py"
Fatal error.
TYPE: <class 'FileNotFoundError'>
DETAILS: [Errno 2] No such file or directory: 'monitored_sites.csv'
TRACEBACK:

File "D:\Python Tasks\robots txt stuff\main.py", line 468, in main
    sites_data = sites_from_file(config.MONITORED_SITES)
  File "D:\Python Tasks\robots txt stuff\main.py", line 26, in sites_from_file
    with open(file, 'r') as sites_file:

Error when updating the main log.
TYPE: <class 'FileNotFoundError'>
DETAILS: [Errno 2] No such file or directory: 'data/main_log.txt'
TRACEBACK:

File "D:\Python Tasks\robots txt stuff\logs.py", line 86, in update_main_log
    with open(config.MAIN_LOG, 'a') as f:

**_Note: I don't have admin privileges to the system which i'm working on.'_**

Thanks
Suresh

_Originally posted by @suri02 in https://github.com/Cmastris/robotstxt-change-monitor/issues/2#issuecomment-781325756_

**Comment by Cmastris** [comment]
Hi @suri02,

I believe this is because task scheduler is looking for the files in the wrong directory, i.e. not in the same directory as main.py. I encountered a similar issue when setting up the cron job on a server.

Have you tried editing the PATH variable as [described here](https://github.com/Cmastris/robotstxt-change-monitor#emails-enabled-server-cron-job-recommended)? Based on the log, I'd try setting the variable to the following: "D:\Python Tasks\robots txt stuff\".

**Comment by suri02** [comment]
> Hi @suri02,
> 
> I believe this is because task scheduler is looking for the files in the wrong directory, i.e. not in the same directory as main.py. I encountered a similar issue when setting up the cron job on a server.
> 
> Have you tried editing the PATH variable as [described here](https://github.com/Cmastris/robotstxt-change-monitor#emails-enabled-server-cron-job-recommended)? Based on the log, I'd try setting the variable to the following:
> 
> `"D:\Python Tasks\robots txt stuff\"`

Hi @Cmastris 

Hey Chris I done the suggested changes in respective files. I'm getting the below error

Checks and reports complete. No change: 4. Change: 0. First run: 0. Error: 1.
Unexpected error in function: send_emails.
TYPE: <class 'NameError'>
DETAILS: name 'SENDER_EMAIL_PASSWORD' is not defined
TRACEBACK:

File "D:\Python Tasks\robots txt stuff\logs.py", line 17, in wrapper
    return func(*args, **kwargs)
  File "D:\Python Tasks\robots txt stuff\emails.py", line 108, in send_emails
    with yagmail.SMTP(config.SENDER_EMAIL, SENDER_EMAIL_PASSWORD) as server:

Unexpected error in function: send_emails.
TYPE: <class 'NameError'>
DETAILS: name 'SENDER_EMAIL_PASSWORD' is not defined
TRACEBACK:

File "D:\Python Tasks\robots txt stuff\logs.py", line 17, in wrapper
    return func(*args, **kwargs)
  File "D:\Python Tasks\robots txt stuff\emails.py", line 108, in send_emails
    with yagmail.SMTP(config.SENDER_EMAIL, SENDER_EMAIL_PASSWORD) as server:

Thank you
Suresh

**Comment by Cmastris** [comment]
@suri02 

Hi Suresh,

`with yagmail.SMTP(config.SENDER_EMAIL, SENDER_EMAIL_PASSWORD) as server:`

You need to replace `SENDER_EMAIL_PASSWORD` with the sender Gmail account password in quotes, e.g. `"MyPassword123"`. Alternatively, you can create a separate variable to store the password in, and reference it.

Thanks,

Chris

**Comment by suri02** [comment]
> @suri02
> 
> Hi Suresh,
> 
> `with yagmail.SMTP(config.SENDER_EMAIL, SENDER_EMAIL_PASSWORD) as server:`
> 
> You need to replace `SENDER_EMAIL_PASSWORD` with the sender Gmail account password in quotes, e.g. `"MyPassword123"`. Alternatively, you can create a separate variable to store the password in, and reference it as the second item within the parenthesis (instead of `SENDER_EMAIL_PASSWORD`).
> 
> Thanks,
> 
> Chris

@Cmastris 

Hi Chris

Thank you, can you please help me on how to do this "**You may need to edit the shebang line at the top of main.py.**" in windows-os.
In terms of errors everything is resolved, program is working fine. I just want to check regarding the shebang code in the main python, how to edit that in windows?

Thank you,
Suresh

**Comment by Cmastris** [comment]
Hi @suri02,

This just related to the Python interpreter/version being used (defined in the first line of the main.py file), but if it's all working then no need to edit it. Glad it's all working now! 👍 

Chris

**Comment by Cmastris** [comment]
Closing this now, but feel free to raise a new issue if you need any more help.
